/**
 * This code runs when the DOM content is ready by adding an event listener
 * to the window object.
 * This script removes the extension (.md) from the autogenerated edit_url.
 * By doing so, the edit button redirects to the valid Netlify CMS resource.
 * 
 */

window.addEventListener("DOMContentLoaded", function() {
    var filteredList = document.querySelectorAll('a.md-content__button.md-icon');

    for(const element of filteredList){
        const ref = element.href;
        if(ref){
            const newRef = ref.replace('.md','');
            element.href = newRef
        }
    }
}, false);
