backend:
  name: github
  repo: renejesusgv/mkdocs-test
  branch: master # Branch to update (optional; defaults to master)
  site_domain: lucid-kare-b81fdc.netlify.com
  site_url: https://renejesusgv.github.io/mkdocs-test
publish_mode: editorial_workflow
media_folder: "site/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "documents" # Used in routes, e.g., /admin/collections/documents
    identifier_field: {{slug}}.md
    label: "Documents" # Used in the UI
    label_singular: "Document"
    folder: "/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "preview/{{slug}}.{{extension}}"
    extension: .md
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Summary"
        name: "summary"
        widget: "text"
      - label: "Sections"
        name: "sections"
        widget: "list"
      - label: "Document Type"
        name: "document-type"
        widget: "select"
        options: 
          - {label: "Tutorial", value: "tutorial"}
          - {label: "Explanation", value: "explanation"}
          - {label: "Reference", value: "reference"}
          - {label: "How-To Guide", value: "how-to-guide"}
      - {label: "Body", name: "body", widget: "markdown"}
