backend:
  name: github
  repo: renejesusgv/mkdocs-test
  branch: master # Branch to update (optional; defaults to master)
  site_domain: lucid-kare-b81fdc.netlify.com
publish_mode: editorial_workflow
media_folder: "site/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "documents" # Used in routes, e.g., /admin/collections/documents
    label: "Document" # Used in the UI
    folder: "/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Sections", name: "sections", widget: "string"}
      - {label: "Document Type", name: "document-type", widget: "select", options: ["tutorial", "explanation", "reference", "how-to-guide"]}
      - {label: "Body", name: "body", widget: "markdown"}