extends: existence
message: "Avoid using plurals in parentheses such as in '%s'."
link: 'https://developers.google.com/style/plurals-parentheses'
level: error
nonword: true
action:
  name: edit
  params:
    - remove
    - '(s)'
tokens:
  - '\b\w+\(s\)'
