extends: existence
message: "Avoid using periods with acronyms or initialisms such as '%s'."
link: 'https://developers.google.com/style/abbreviations'
level: error
nonword: true
tokens:
  - '\b(?:[A-Z]\.){3,}'
