extends: existence
message: "'%s' must only have one space."
link: 'https://developers.google.com/style/sentence-spacing'
level: error
nonword: true
tokens:
  - '[a-z][.?!] {2,}[A-Z]'
  - '[a-z][.?!][A-Z]'
