extends: existence
message: "Avoid using first-person plural like '%s'. Describe the person instead."
link: 'https://developers.google.com/style/pronouns#personal-pronouns'
level: error
ignorecase: true
tokens:
  - we
  - we'(?:ve|re)
  - ours?
  - us
  - let's
