extends: existence
message: "Avoid using '%s'. Consider using the present form of the verb to avoid uncertainty."
link: 'https://developers.google.com/style/tense'
ignorecase: true
level: warning
tokens:
  - will
