# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Pull request from a labeled issue.
on:
  issues:
    types:
      - labeled
jobs:
  create-pr:
    if: github.event.label.name == 'publish-request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     cache: 'npm'
      #     cache-dependency-path: .github/actions/get-pr-metadata/package-lock.json
      # - run: npm install .github/actions/get-pr-metadata
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
           This issue will create a new PR -- wait for it...

      - id: pr-metadata
        uses: ./.github/actions/get-pr-metadata
        continue-on-error: true

######## Step error
      - name: Check outputs on error
        if: steps.pr-metadata.outcome != 'success'
        run: |
          echo "Please, add a title in your metadata and try again."
  
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        if: steps.pr-metadata.outcome != 'success'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please, add a title in your metadata and try again.
      
      - name: Remove publish-request label
        uses: szollarp/remove-label-from-issue-action@v1
        if: steps.pr-metadata.outcome != 'success'
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          labels: publish-request
          issueNumber: ${{ github.event.issue.number }}

      - name: Add action required label
        uses: szollarp/add-label-to-issue-action@v1
        if: steps.pr-metadata.outcome != 'success'
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          labels: action-required
          issueNumber: ${{ github.event.issue.number }}

      - name: Exit on failure
        if: steps.pr-metadata.outcome != 'success'
        run: exit 1
 ##########
      - name: Commits new file
        run: |
          echo "${{ steps.pr-metadata.outputs.body }}" > ${{ steps.pr-metadata.outputs.fileName }}
          mv ${{ steps.pr-metadata.outputs.fileName }} docs/
#          rm package-lock.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          commit-message: New file created by ${{ github.actor }} from issue ${{ github.event.issue.number }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ steps.pr-metadata.outputs.branchName }}
          base: master
          delete-branch: true
          title: ${{ steps.pr-metadata.outputs.title }}
          body: |
            - Auto-generated by [create-pull-request] action from issue ${{ github.event.issue.number }}
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Pull Request Number created - ${{ steps.cpr.outputs.pull-request-number }}
            Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}
      - name: Remove publish-request label
        uses: szollarp/remove-label-from-issue-action@v1
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          labels: publish-request
          issueNumber: ${{ github.event.issue.number }}
      - name: Add in-review label
        uses: szollarp/add-label-to-issue-action@v1
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          labels: in-review
          issueNumber: ${{ github.event.issue.number }}
