# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'review' && github.actor == 'renejesusgv'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
           This issue will create a new PR -- wait for it...

      - name: Dash name
        run: |
          DASHED_NAME=$(node -e 'require("./scripts/helpers").toDashCase("some string")')
          echo "$DASHED_NAME"

      - name: View the github context
        run: echo "$DASHED_NAME"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "test-file.md"
          FILE_DATA: ${{ github.event.issue.body }}    
      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #   # Create secret and uncomment if I want to trigger more GH actions in a PR
      #     token: ${{ secrets.GIT_TOKEN }}
      #     commit-message: new file created by ${{ github.actor }} from ${{ github.event.issue.number }}
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: example-file
      #     base: main
      #     delete-branch: true
      #     title: '[Example] Update report'
      #     body: |
      #       New file 
      #       - Auto-generated by [create-pull-request][1] from issue ${{ github.event.issue.number }}
      #     draft: false

      # - name: Check outputs
      #   run: |
      #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
      #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      # - name: Add comment
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       Pull Request Number created - ${{ steps.cpr.outputs.pull-request-number }}
      #       Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}
# You also can print the whole github context to the logs to view more details.            
