# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'review' && github.actor == 'renejesusgv'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: scripts/package-lock.json
      - run: npm install
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
           This issue will create a new PR -- wait for it...

      - id: pr-metadata
        uses: ./.github/actions/get-pr-metadata
        # run: ${{ steps.pr-metadata.outputs.body }} > ${{ steps.pr-metadata.outputs.title }}.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          commit-message: new file created by ${{ github.actor }} from ${{ github.event.issue.number }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ steps.pr-metadata.outputs.branchName }}
          base: master
          delete-branch: true
          title: ${{ steps.pr-metadata.outputs.title }}
          body: |
            ${{ steps.pr-metadata.outputs.body }}
            - Auto-generated by [create-pull-request][1] from issue ${{ github.event.issue.number }}
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Pull Request Number created - ${{ steps.cpr.outputs.pull-request-number }}
            Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}
# You also can print the whole github context to the logs to view more details.            
