name: Vale
on:
  pull_request:
    branches: [main]

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]  
    steps: 

      - name: Checkout main
        uses: actions/checkout@v2

      - name: vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          files: __onlyModified
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
